log:
  level: DEBUG
  console_output: true

max_image_size: 10

listen:
  host: 0.0.0.0
  port: 8080
  server_mode: "REST"
  max_request_size: 10
  max_response_size: 10

minio:
  endpoint: "localhost:9000"
