log:
  level: DEBUG
  console_output: true

max_image_size: 10

app:
  id: images_storage
  version: 1.0.0

listen:
  host: 0.0.0.0
  port: 8080
  server_mode: "REST"
  max_request_size: 10
  max_response_size: 10

minio:
  endpoint: "host.docker.internal:9000"
